version: "3"

services:
  logstashs:
    build:
      context: .
    container_name: logstashs
    depends_on:
      - elasticsearch
      - nominatim
    restart: always

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.3
    ports:
      - "8080:8080"
      - "8888:5432"
    environment:
      PBF_PATH: ${PBF_PATH}
      NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD}
    volumes:
      - /osm-maps/data:/nominatim/data

  elasticsearch:
    container_name: elastic
    image: elasticsearch:8.12.1
    depends_on:
      - nominatim
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}